package com.dementia.neurocraft.common.features;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * AUTO-GENERATED: Shared registry of all feature IDs that can be accessed from both client and server.
 * This prevents server configs from depending on client-only classes.
 * 
 * Generated by FeatureRegistryGenerator - DO NOT EDIT MANUALLY!
 */
public class FeatureRegistry {

    public static final List<String> CLIENT_FEATURE_IDS = Arrays.asList(
        "PSYCHOSIS",
        "ITEMS_LOSE_LETTERS",
        "REPLACE_ITEMS_IN_INVENTORY",
        "RANDOMIZE_BARS",
        "RANDOMIZE_XP",
        "ENEMY_HALLUCINATIONS",
        "OPTION_FOV_CHANGES",
        "OPTION_BRIGHTNESS_CHANGES",
        "OPTION_FRAMERATE_CHANGES",
        "OPTION_RENDER_DISTANCE_CHANGES",
        "OPTION_CONTROL_SWAPS",
        "PLAYER_DISORIENTATION",
        "MOB_SPAWN_RANDOMIZATION"
    );

    public static final List<String> SERVER_FEATURE_IDS = Arrays.asList(
        "AUDITORY_HALLUCINATIONS",
        "FAKE_BREAK_BLOCKS",
        "FAKE_PLACE_BLOCKS",
        "EATING_DISORDER",
        "FURNACE_UNCOOKING",
        "ITEMS_SWAP_POSITIONS_IN_INVENTORY",
        "ORE_HALLUCINATIONS",
        "RANDOM_TELEPORTING",
        "ENEMY_HALLUCINATIONS"
    );

    /**
     * Get all feature IDs (both client and server)
     */
    public static List<String> getAllFeatureIds() {
        List<String> allIds = new ArrayList<>(CLIENT_FEATURE_IDS);
        // Add server IDs that aren't already in client list
        SERVER_FEATURE_IDS.forEach(id -> {
            if (!allIds.contains(id)) {
                allIds.add(id);
            }
        });
        return allIds;
    }
}
